### ISSUE TITLE
Targeting 4.7 and 4.6 latest rotativa from Nuget not working --  type or namespace name 'Rotativa' could not be found (are you missing a using directive or an assembly reference?)	

### ISSUE THREAD

**Issue by weedkiller** [webgio/Rotativa#199]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Rotativa' could not be found (are you missing a using directive or an assembly reference?)	ReaLocate.Web	c:\Test\Web\Controllers\InvoicesController.cs	12	Active

**Comment by Yantup** [comment]
You need to install this version:
[Rotativa](https://www.nuget.org/packages/Rotativa/1.7.4-rc)
It was solved in another issue, but i dont know how to refer the thread.

**Comment by weedkiller** [comment]
Hello,t hanks for the response, I tried it with the RC version and i still get the error

**Comment by zw-gb** [comment]
What was the solution for this?
The rc version did not fix my issue as well.

**Comment by ericfelipe99** [comment]
> What was the solution for this?
> The rc version did not fix my issue as well.

I had the same problem with nuget package install... 
you could try to reference Rotativa's DLL manually. Justo go to your solution folder, find the package folder, rotativa folder and find it's DLL and reference it in your project.

**Comment by weedkiller** [comment]
it doest work for 4.8 either, the issue continues

**Comment by khalidfahmy98** [comment]
Open References and right click on Rotative -> properties  copy the path 

then right click on reference choose browse and paste the path above in the windows explorer make sure to remove the last rotative.dll file from the end of path 

after  that choose the dll file it would be the only  then click ok  - > ok and you are good to go 

that worked for me
